### ISSUE TITLE
[v2] Verify logic for top CVEs in attack path

### ISSUE THREAD

**Issue by jatin-baweja** [deepfence/ThreatMapper#1341]
**Describe the bug**
Currently, CVEs with higher score are being ignored in top CVEs under attack path.

**To Reproduce**
1. Go to 'Vulnerabilities' section
2. Click on 'See All Scans'
3. Click on any of the host/container/image to show its latest complete scan details
4. Hover on the node inside the 'Top Attack paths' graph to check the Top CVEs

**Expected behavior**
Higher scored CVEs should be shown in attack path. Also, only CVE ID should be shown instead of the id being shown currently

**Screenshots**
![top_cves_in_attack_path](https://github.com/deepfence/ThreatMapper/assets/4747605/60c98612-f47a-400c-ad69-f90788972cca)

**Components/Services affected**

- [x] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by manV** [comment]
IDK about the logic for attack path, top vulnerabilities are just top 5 vulnerabilities in this scan sorted by cvss score.

**Comment by varunsharma0286** [comment]
@jatin-baweja 
* The CVE's shown on the top attack path looks correct. 
Reason being the top CVE's shown in the "Top Attack Path" are supposed to be based on the exploitability score (due to network connections).  
* I have made the change to show only the CVE ID in the top attack path vulnerabilities
PR:  https://github.com/deepfence/ThreatMapper/pull/1385
