### ISSUE TITLE
[V2] Topology Cloud table displays internet as a node

### ISSUE THREAD

**Issue by milan-deepfence** [deepfence/ThreatMapper#1363]
**Describe the bug**
Topology cloud table has an entry for internet however clicking on it removes its row appearance 

**To Reproduce**
1. Go to Topology view
2. Click on Table view mode
3. You will see internet has a name in a row
4. Click on it and row vanish away

**Expected behavior**
Internet row presence seems not necessary

**Screenshots**
<img width="1919" alt="Screenshot 2023-07-18 at 6 00 04 PM" src="https://github.com/deepfence/ThreatMapper/assets/111341101/ffcdcde2-1dcf-4242-a629-072dc882f8b3">
<img width="1918" alt="Screenshot 2023-07-18 at 6 00 16 PM" src="https://github.com/deepfence/ThreatMapper/assets/111341101/d84259b2-4fe3-43df-b126-7b28820ff057">

**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by shyam-dev** [comment]
Yes, we need not show a row for internet.

**Comment by manV** [comment]
@shyam-dev this needs to be fixed from the API side

**Comment by gnmahanth** [comment]
@ramanan-ravi @noboruma @shyam-dev  this query returns internet as cloud provider node, not sure why is there as cloud provider `internet` https://github.com/deepfence/ThreatMapper/blob/49c946a6e82a0f30883e5d7cfdb18a67b32e8790/deepfence_server/reporters/graph/topology_reporter.go#L518

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/1cc22174-fd7a-4347-968e-2ff137b4f876)

**Comment by noboruma** [comment]
This is caused by the linking task which extract and attach cloud providers asynchronously.
To prevent that, we need to filter out the internet cloud provider directly from the cronjob job associated with linking.

Context: internet nodes are added when we initialize the DB. Previously cloud providers were added at the same time as nodes were added. It was a sync process that never happened for internet nodes as their addition is treated specially.
