### ISSUE TITLE
[v2] Integrations S3 and Jira missing advanced filters

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#1440]
**Describe the bug**
S3 and Jira are missing the advanced filters available in other integrations

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/201736c3-f835-4f9a-9a57-628559bb916f)

**Comment by milan-deepfence** [comment]
In V1, I do not see advanced filters for S3 and Jira, do we need to enable for these two?
<img width="1024" alt="Screenshot 2023-08-07 at 2 42 18 PM" src="https://github.com/deepfence/ThreatMapper/assets/111341101/72fec3cd-e30d-4381-b803-cf7b81b0fcfd">

**Comment by shyam-dev** [comment]
We do need advanced filters for JIRA

**Comment by varunsharma0286** [comment]
This issue has been fixed in the latest V2 codebase 
I can see the advanced filters in both the S3 and JIRA integrations:
<img width="562" alt="image" src="https://github.com/deepfence/ThreatMapper/assets/6186285/2ce45b97-dace-4d3e-b240-8e7892f405c1">
<img width="587" alt="image" src="https://github.com/deepfence/ThreatMapper/assets/6186285/55ef4b3b-8a51-4c1a-82ae-03584ad460a8">
