### ISSUE TITLE
[V2] Access Docker hub public repositories without credentials

### ISSUE THREAD

**Issue by saurabh2253** [deepfence/ThreatMapper#1481]
User should be able to add public registries without adding docker hub credentials.

Remove validation from registry add request and make  api login optional to docker hub .
**Components/Services**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by saurabh2253** [comment]
UI is sending node_type:"container_image" instead of "image"

**Comment by manV** [comment]
We should have a boolean flag in the API for public registry ideally. Because if its not public we need to do the validation on username/password fields. If we just make them optional, user might get an impression that they can enter username but not password or the other way around.

Thoughts @saurabh2253 ?

**Comment by saurabh2253** [comment]
This flag does not solve anything for us, the username / password would anyway be validated if there is any value. e.g. You cannot put single character in uname/ pwd else empty string would be ignored

**Comment by manV** [comment]
We anyways added the checkbox and now hiding credentials fields from the ui if checkbox is ticked, just to be consistent with ECR public registry forms.
