### ISSUE TITLE
Incorrect graph counts when filters are applied

### ISSUE THREAD

**Issue by shyam-dev** [deepfence/ThreatMapper#2105]
**Describe the bug**

When filters are applied to posture scan results, the counts in the graph do not reflect the filters.

**To Reproduce**

Please see the attached video

**Expected behavior**

When filters are applied, the corresponding counts must also change.

- [x] UI/Frontend
- [x] API/Backend

https://github.com/deepfence/ThreatMapper/assets/1436408/906df115-2a57-440b-b7da-4600fd1e281c

**Comment by milan-deepfence** [comment]
Related with https://github.com/deepfence/ThreatMapper/issues/2101. 
This issue is known one where we do not have cross filter across charts and count.
By looking in api request and response, api is same both for table and charts and count. Status count values do not consider filter payload. @ibreakthecloud @manV

**Comment by ramanan-ravi** [comment]
@milan-deepfence @manV Filters need to be added to the following graph also

I don't see the filters set in the api request for this graph.

![image](https://github.com/deepfence/ThreatMapper/assets/38394463/5988ee3d-d87d-4ffe-8ab7-d0ce9521ecb8)
