### ISSUE TITLE
[Email Configuration] remove auto-filling of email id

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#80]
**Describe the bug**
Email Configuration Email and Password field gets auto-filled

**To Reproduce**
1. Go to Settings-->Email Configuration
2. Enter all fields required for Google SMTP and click on Save
3. Refresh the page.

**Expected behavior**
 You will see that the email and password is auto-filled. Please remove it.

**Screenshots**
![image](https://user-images.githubusercontent.com/34362153/138923967-132fbec3-1b41-433c-9de8-506a33e765a9.png)

**Components/Services affected**

- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by ibreakthecloud** [comment]
there is no definite solution proposed for this yet. Although there are certain hacks to achieve the same, which has it's own downside. Currently I am not planning to put any hack or try to fix this. Anyways it's not a security risk since it doesn't autofill unless user saves the password.
ref: https://stackoverflow.com/a/41217255

A very long Chromium thread for this: https://bugs.chromium.org/p/chromium/issues/detail?id=468153

Feel free to close it or move it to `wontfix`
